config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :signup, only: [:new, :create] do
    collection do
      post 'step'  #入力が全て完了
      get 'complete_signup'  #登録完了後
    end
  end
  resources :products do 
    collection do
      get 'category_children', defaults: { format: 'json' } 
      get 'category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
    end
  end
  resources :users, only: [:index, :show]
  resources :credits, only: [:new, :create, :show] do
    member do
      post 'delete', to: 'credits#delete'
      post 'pay', to: 'credits#pay'
      get 'done', to: 'credits#done'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  # validates :postcode, :prefecture_id, :city, :housenumber, :housename, :phonenumber, presence: true
  # validates :user, presence: true
  # validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
  ]
end

app/models/fee.rb
class Fee < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み(出品者負担)'}, {id: 2, name: '着払い(購入者負担)'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product

  validates :image, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/payer.rb
class Payer < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み(出品者負担)'}, {id: 2, name: '着払い(購入者負担)'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :images, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  has_one :delivery
  has_one :todo
  belongs_to_active_hash :condition
  belongs_to_active_hash :payer
  belongs_to_active_hash :shippingaddress
  belongs_to_active_hash :shippingdate
  belongs_to_active_hash :size
  
  validates :name, presence: true
  validates :detail, presence: true
  validates :size, presence: true
  validates :price, presence: true
  validates :condition, presence: true
  validates :shippingaddress, presence: true
  validates :shippingdate, presence: true
  validates :payer, presence: true  
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :images, presence: true
  

  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/shippingdate.rb
class Shippingdate < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
  ]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, name: 'XXS以下'},{id: 2, name: 'XS(SS)'},{id: 3, name: 'S'},{id: 4, name: 'M'},{id:5, name: 'L'},
    {id: 6, name: 'XL(LL)'},{id: 7, name: '2XL(3L)'},{id: 8, name: '3XL(4L)'},{id: 9, name: '4XL(5L)以上'},{id: 10, name: 'FREE SIZE'}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :nickname, :lastname, :firstname, :lastnamekana, :firstnamekana, :birthday, presence: true
  # validates :address, presence: true
  has_many :comments, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :credits, dependent: :destroy
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address, update_only: true
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :save_new_to_session, only: :step

  def new
    @user = User.new
    @user.build_address
  end

  def save_new_to_session
    session[:user_params] = user_params
    session[:address_attributes_after_new] = user_params[:address_attributes]
    @user = User.new(session[:user_params])
    @user.build_address(session[:address_attributes_after_new])
    redirect_to new_signup_path unless @user.valid?
  end 

  def step
    @user = User.new
    @user.build_address
  end

  def create
    @user = User.new(session[:user_params])
    @user.build_address(session[:address_attributes_after_new])
    @user.build_address(user_params[:address_attributes])
    if @user.save
      sign_in(@user)
      redirect_to complete_signup_signup_index_path
    else
      redirect_to new_signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :nickname, 
      :email, 
      :password, 
      :lastname, 
      :firstname, 
      :lastnamekana, 
      :firstnamekana, 
      :birthday, 
      address_attributes: [:id, :postcode, :prefecture_id, :city, :housenumber, :housename, :phonenumber]
    )
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/credts_helper.rb
module CredtsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/signup/complete_signup.html.haml
.body
  .registration__ok
    .registration__ok__text
      登録が完了しました
    .registration__ok__btnbtn
      = link_to "トップへ戻る", root_path, class: 'registration__ok__btn__home'

app/views/signup/new.html.haml
.box
  .header
    = link_to image_tag("/images/logo/logo.png", width: '120px', alt: "logo1"),root_path

  .main
    .main__login
      .main__login__account
        会員情報入力
      .main__login__info
        = form_with model: @user, url: step_signup_index_path, id: 'user', class: 'new_user', local: true do |f|
          .box__group
            .box__group__title
              ニックネーム
            .box__group__hisu
              必須
          .box__form
            = f.text_field :nickname, placeholder: "(例)メルカリ太郎", class: "name__text"
          .box__group
            .box__group__title
              メールアドレス
            .box__group__hisu
              必須
          .box__form
            = f.email_field :email, placeholder: "PC・携帯どちらでも可", class: "name__text"
          .box__group
            .box__group__title
              パスワード
            .box__group__hisu
              必須
          .box__form
            = f.password_field :password, placeholder: "7文字以上の半角英数字", class: "name__text"
          .box__mark
            ※ 英字と数字の両方を含めて設定してください
          .box__check
            = f.text_field :checkbox, type: "checkbox", class: "btn__check"
            .box__check__text
              パスワードを表示する
          .box__confirm
            .box__confirm__name
              本人確認
            .box__confirm__text
              安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
          .box__group
            .box__group__title
              お名前(全角)
            .box__group__hisu
              必須
          .box__form
            .box__form__text
              = f.text_field :lastname, placeholder: "例)山田", class: "lastname"
            .box__form__text
              = f.text_field :firstname, placeholder: "例)太郎", class: "firstname"
          .box__group
            .box__group__title
              お名前カナ(全角)
            .box__group__hisu
              必須
          .box__form
            .box__form__text
              = f.text_field :lastnamekana, placeholder: "例)ヤマダ", class: "lastname"
            .box__form__text
              = f.text_field :firstnamekana, placeholder: "例)タロウ", class: "firstname"
          .box__group
            .box__group__title
              生年月日
            .box__group__hisu
              必須
          .box__form
            .box__form__text
              = f.date_select :birthday, with_css_classes:"", start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989, 1, 1), use_month_numbers: true
          .box__mark
            ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .box__next
            「次へ進む」のボタンを押すことにより、利用規約に同意したものとみなします
          .main__login__info__button
            = f.submit "次へ進む"
          .box__english
            This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.

  .footer
    .footer__box
      .footer__box__text
        プライバシーポリシー
      .footer__box__message
        メルカリ利用規約
      .footer__box__form
        特定商取引に関する表記
    .footer__logo
      mercari
      .footer__logo__text
        © Mercari, Inc.

app/views/signup/step.html.haml
.addressMain
  .addressMain__login
    .addressMain__login__account
      会員情報入力  
    .addressMain__login__form
      = form_with model: @user, url: signup_index_path, id: 'user', class: 'new_address', local: true do |f|
        = f.fields_for :address do |ff|
          .address
            .address__postCode
              .address__postCode__info
                郵便番号
                %sp 必須
              .address__postCode__form
                = ff.text_field :postcode, placeholder: '(例) 111-111', class: 'address_form'

            .address__prefectures
              .address__prefectures__info
                都道府県
                %sp 必須
              .address__prefectures__form
                = ff.collection_select :prefecture_id, Prefecture.all, :id, :name, include_blank: '--', class: 'select-default'

            .address__city
              .address__city__info
                市区町村
                %sp 必須
              .address__city__form
                = ff.text_field :city, placeholder: '(例) 新宿区神南',class: 'address_form'
              
            .address__houseNumber
              .address__houseNumber__info
                番地
                %sp 必須
              .address__houseNumber__form
                = ff.text_field :housenumber, placeholder: '(例) 1丁目18−2', class: 'address_form'

            .address__houseName
              .address__houseName__info
                アパート名・住宅名
                %sp 必須
              .address__houseName__form
                = ff.text_field :housename, placeholder: '(例) フレーム神南坂4階', class: 'address_form'


            .address__phoneNumber
              .address__phoneNumber__info
                電話番号
                %sp 必須
              .address__phoneNumber__form
                = ff.text_field :phonenumber, placeholder: '(例) 09012345678',class: 'address_form'
          
            .address__action
              .address__action__submit
                = ff.submit "会員登録", class: 'address_btn'