config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :signup, only: [:new, :create] do
    collection do
      post 'step'  #入力が全て完了
      get 'complete_signup'  #登録完了後
    end
  end
  resources :products do 
    collection do
      get 'category_children', defaults: { format: 'json' } 
      get 'category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
    end
  end
  resources :users, only: [:index, :show]
  resources :credits, only: [:new, :create, :show] do
    member do
      post 'delete', to: 'credits#delete'
      post 'pay', to: 'credits#pay'
      get 'done', to: 'credits#done'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  # validates :postcode, :prefecture_id, :city, :housenumber, :housename, :phonenumber, presence: true
  # validates :user, presence: true
  # validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
  ]
end

app/models/fee.rb
class Fee < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み(出品者負担)'}, {id: 2, name: '着払い(購入者負担)'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product

  validates :image, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/payer.rb
class Payer < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み(出品者負担)'}, {id: 2, name: '着払い(購入者負担)'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :images, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  has_one :delivery
  has_one :todo
  belongs_to_active_hash :condition
  belongs_to_active_hash :payer
  belongs_to_active_hash :shippingaddress
  belongs_to_active_hash :shippingdate
  belongs_to_active_hash :size
  
  validates :name, presence: true
  validates :detail, presence: true
  validates :size, presence: true
  validates :price, presence: true
  validates :condition, presence: true
  validates :shippingaddress, presence: true
  validates :shippingdate, presence: true
  validates :payer, presence: true  
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :images, presence: true
  

  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/shippingaddress.rb
class Shippingaddress < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/shippingdate.rb
class Shippingdate < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
  ]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, name: 'XXS以下'},{id: 2, name: 'XS(SS)'},{id: 3, name: 'S'},{id: 4, name: 'M'},{id:5, name: 'L'},
    {id: 6, name: 'XL(LL)'},{id: 7, name: '2XL(3L)'},{id: 8, name: '3XL(4L)'},{id: 9, name: '4XL(5L)以上'},{id: 10, name: 'FREE SIZE'}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :nickname, :lastname, :firstname, :lastnamekana, :firstnamekana, :birthday, presence: true
  # validates :address, presence: true
  has_many :comments, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :credits, dependent: :destroy
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address, update_only: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  
  def show
  end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/credts_helper.rb
module CredtsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.haml
.navigation
  %ul.mypage
    %li
      = link_to 'マイページ', '/users/(current_user.id)', class: 'mypage_top'
    %li
      = link_to 'お知らせ','#' , class: 'mypage_list'
    %li
      = link_to 'やることリスト','#', class: 'mypage_list'
    %li
      = link_to 'いいね！一覧','#', class: 'mypage_list'
    %li
      = link_to '出品する','#', class: 'mypage_list'
    %li
      = link_to '出品した商品-出品中','#', class: 'mypage_list'
    %li
      = link_to '出品した商品–取引中','#', class: 'mypage_list'
    %li
      = link_to '出品した商品–売却済み','#', class: 'mypage_list'
    %li
      = link_to '購入した商品–取引中','#', class: 'mypage_list'
    %li
      = link_to '購入した商品–過去の取引','#', class: 'mypage_list'
    %li
      = link_to 'ニュース一覧','#', class: 'mypage_list'
    %li
      = link_to '評価一覧','#', class: 'mypage_list'
    %li
      = link_to 'ガイド','#', class: 'mypage_list'
    %li
      = link_to 'お問い合わせ','#', class: 'mypage_list'

  .merpay
    %h3
      メルペイ
    %ul
      %li
        = link_to '売上・振込申請','#', class: 'merpay_list'
      %li
        = link_to 'ポイント','#', class: 'merpay_list'

  .setting
    %h3
      設定
    %ul
      %li
        = link_to 'プロフィール', '#', class: 'setting_list'
      %li
        = link_to '発送元・お届け先住所変更','#', class: 'setting_list'
      %li
        = link_to 'カード登録・確認', '/credits/(current_user.id)', class: 'setting_list'
      %li
        = link_to 'メール/パスワード','#', class: 'setting_list'
      %li
        = link_to '本人情報','#', class: 'setting_list'
      %li
        = link_to '電話番号の確認','#', class: 'setting_list'
      %li
        = link_to 'ログアウト', users_path, class: 'setting_list'

app/views/users/index.html.haml
.header
  = render "products/header"

.body
  .left_content
    = render partial: 'sidebar'
  .right_content
    .logout
      .logout_btn
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'sign_out_btn'

.footer
  部分テンプレート

app/views/users/show.html.haml
.header
  = render 'products/header'
.body
  .left_content
    = render partial: 'sidebar'
  
  .right_content
    .user
      .user_info
        %h2.user_info__name
          = current_user.nickname
          さん
        %ul.user_info__products
          %li.user_info__products__status 評価0
          %li.user_info__products__length 出品数
      .user_topic
        %ul.tab
          %li.active お知らせ
          %li やることリスト
        .area
          %ul.show
            = link_to 'ニュース','#', class: 'topic'
            = link_to '一覧表示','#', class: 'all'

          %ul
            = link_to 'やること','#', class: 'todo'
            = link_to '一覧表示','#', class: 'all'

    .products
      %h3 購入した商品
      .products__list
        %ul.tab
          %li.active 取引中
          %li 過去の取引
        .area
          %ul.show
            = link_to 'カバン','#', class: 'deal'
            
          %ul
            = link_to '靴','#', class: 'past'
.footer
  = render 'products/footer'