config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :signup, only: [:new, :create] do
    collection do
      post 'step'  #入力が全て完了
      get 'complete_signup'  #登録完了後
    end
  end
  resources :products do 
    collection do
      get 'category_children', defaults: { format: 'json' } 
      get 'category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
    end
  end
  resources :users, only: [:index, :show]
  resources :credits, only: [:new, :create, :show] do
    member do
      post 'delete', to: 'credits#delete'
      post 'pay', to: 'credits#pay'
      get 'done', to: 'credits#done'
    end
  end
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController

  require 'payjp'
  Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
          
  def new
    
  end

  def create  
    if params["payjpToken"].blank?
      redirects_to new_credit_path
    else
      customer = Payjp::Customer.create(
      card: params['payjpToken'],
      )

      @credit = Credit.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @credit.save
        redirect_to user_path(id: current_user.id)
      else
        render new_credit_path
      end
    end
  end

  def show
    card = Credit.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to new_credit_path
    else
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card_information = customer.cards.retrieve(card.card_id)
    end
  end 

  def delete
    card = Credit.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to new_credit_path
    else
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
      redirect_to user_path(id: current_user.id)
    end
  end

  def pay
    card = Credit.find_by(user_id: current_user.id)
    @product = Product.find(params[:id])
    if card.blank?
      redirect_to new_credit_path, alert: 'ERROR!!'
    else
      Payjp::Charge.create(
      amount: @product.price,
      customer: card.customer_id,
      currency: 'jpy'
      )
      if @product.update(status_id: 1, buyer: current_user.id)
        redirect_to action: 'done'
        flash[:notice] = '購入しました。'
      else
        flash[:alert] = '購入に失敗しました。'
        redirect_to root_path
      end
    end
  end

  def done
  end
  
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/done.html.haml
.header
  = render 'products/header'
.body
  .left_content
    = render 'users/sidebar'
  .right_content
    .credit_done
      購入完了しました。
      .credit_done__btn
        = link_to 'TOPへ戻る',root_path , class: 'home_btn'

app/views/credits/new.html.haml
.header
  = render "products/header"
  
.body
  .left_content
    = render 'users/sidebar'
  .credits
    .credits_form
      .credits_form__label
        クレジットカード情報入力
      .credits_form__box
        = form_with url: credits_path, id: 'credit_form', local: true do |f|
          .credits_form__box__number
            = f.label :カード番号, class: 'form_label'
            %span.caution 必須

          .credits_form__box__input
            = f.text_field :number, class: 'credit__input', id: 'number', maxlength: "16", placeholder: "半角数字のみ"
            .registration_error{type: "hidden", value: "必須項目です"}
          %ul
            %li= image_tag '/credits/visa.svg', height:"20px", wight: "auto", alt: 'visa', class: 'credits_icon'
            %li= image_tag '/credits/master-card.svg', height:"20px", wight: "auto", alt: 'aster-card', class: 'credits_icon'
            %li= image_tag '/credits/saison-card.svg', height:"20px", wight: "auto", alt: 'saison-card', class: 'credits_icon'
            %li= image_tag '/credits/jcb.svg', height:"20px", wight: "auto", alt: 'visa', class: 'credits_icon'
            %li= image_tag '/credits/american_express.svg', height:"20px", wight: "auto", alt: 'american_express', class: 'credits_icon'
            %li= image_tag '/credits/dinersclub.svg', height:"20px", wight: "auto", alt: 'dinersclub', class: 'credits_icon'
            %li= image_tag '/credits/discover.svg', height:"20px", wight: "auto", alt: 'discover', class: 'credits_icon'

          .credits_form__box__expiredate
            = f.label :有効期限, class: 'form_label'
            %span.caution 必須
            .credits_expiredate
              = f.select :card_month, options_for_select(["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]), {}, {class: "month_select"}
              = f.label :月, class: "form-group__card--year-and-month"
              = f.select :card_year, options_for_select((2020..2030)), {}, {class: "year_select"}
              = f.label :年, class: "form-group__card--year-and-month"

          .credits_form__box__securitycode
            = f.label :セキュリティーコード, class: 'form_label'
            %span.caution 必須
            = f.text_field :securitycode, class: 'credit__input', id: "cvc", maxlength: "4" ,placeholder: "カード背面４桁もしくは３桁の番号"
          .credits_form__box__question
            .credits_form__box__question__text 
              カード裏面の番号とは？
          .credits_form__box__send#card_token
            = f.submit "追加する", class: "credit_send_btn", id: "credits_send_btn"
          #result

.footer
  = render 'products/footer'

app/views/credits/show.html.haml
.header
  = render "products/header"
.body
  .left_content
    = render 'users/sidebar'
  .credits
    .credits_show
      .credits_show__label
        支払い方法
      .credits_show__main
        .credits_show__main__head
          クレジットカード一覧
        .credits_show__main__body
          %ul.credits_show__main__body__top
            %li= image_tag '/credits/visa.svg', height:"15px", wight: "auto", alt: 'visa', class: 'credits_icon'
            %li= link_to '削除する', delete_credit_path, method: :post, class: 'credits_delete_btn'
          .credits_show__main__body__middle
            **** **** **** #{@card_information.last4}
          .credits_show__main__body__bottom
            - exp_month = @card_information.exp_month.to_s
            - exp_year = @card_information.exp_year.to_s.last(2)
            = exp_month + ' / ' + exp_year
                  
        .credits_show__main__footer
          .credits_show__main__footer__about
            = link_to '支払い方法について  >>', '#', class: 'credits_show__main__footer__about__btn'

.footer
  = render 'products/footer'