config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :signup, only: [:new, :create] do
    collection do
      post 'step'  #入力が全て完了
      get 'complete_signup'  #登録完了後
    end
  end
  resources :products do 
    collection do
      get 'category_children', defaults: { format: 'json' } 
      get 'category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
    end
  end
  resources :users, only: [:index, :show]
  resources :credits, only: [:new, :create, :show] do
    member do
      post 'delete', to: 'credits#delete'
      post 'pay', to: 'credits#pay'
      get 'done', to: 'credits#done'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  # validates :postcode, :prefecture_id, :city, :housenumber, :housename, :phonenumber, presence: true
  # validates :user, presence: true
  # validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
  ]
end

app/models/fee.rb
class Fee < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み(出品者負担)'}, {id: 2, name: '着払い(購入者負担)'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product

  validates :image, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/payer.rb
class Payer < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み(出品者負担)'}, {id: 2, name: '着払い(購入者負担)'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :images, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  has_one :delivery
  has_one :todo
  belongs_to_active_hash :condition
  belongs_to_active_hash :payer
  belongs_to_active_hash :shippingaddress
  belongs_to_active_hash :shippingdate
  belongs_to_active_hash :size
  
  validates :name, presence: true
  validates :detail, presence: true
  validates :size, presence: true
  validates :price, presence: true
  validates :condition, presence: true
  validates :shippingaddress, presence: true
  validates :shippingdate, presence: true
  validates :payer, presence: true  
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :images, presence: true
  

  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/shippingdate.rb
class Shippingdate < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
  ]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, name: 'XXS以下'},{id: 2, name: 'XS(SS)'},{id: 3, name: 'S'},{id: 4, name: 'M'},{id:5, name: 'L'},
    {id: 6, name: 'XL(LL)'},{id: 7, name: '2XL(3L)'},{id: 8, name: '3XL(4L)'},{id: 9, name: '4XL(5L)以上'},{id: 10, name: 'FREE SIZE'}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷や汚れなし'},{id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :nickname, :lastname, :firstname, :lastnamekana, :firstnamekana, :birthday, presence: true
  # validates :address, presence: true
  has_many :comments, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :credits, dependent: :destroy
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address, update_only: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only:["destroy", "show", "edit", "update", "confirm"]

  def index
    @product = Product.includes(:images).where(status_id: 0).last(10)
    @products = Product.includes(:images).where(status_id: 1).limit(10).order('created_at DESC')
  end

  def new
    @category = Category.where(ancestry: nil).each do |parent|
    end
    @product = Product.new
    @product.images.build
  end

  def category_children  
    @category_children = Category.find(params[:productcategory]).children 
  end

  def category_grandchildren
    @category_grandchildren = Category.find(params[:productcategory]).children
  end

  
  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  def edit
    @category = Category.where(ancestry: nil).each do |parent|
    end
  end
  
  def update
    if @product.update(product_params)
       redirect_to root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
    if @product.destroy
      redirect_to root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def confirm
    @card = Credit.find_by(user_id: current_user.id)
  end

  def show

  end

private

  def product_params
    params.require(:product).permit(:name, :detail, :category_id, :size_id, :condition_id, :payer_id, :shippingaddress_id, :shippingdate_id, :price, images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.includes(:images).find(params[:id])
  end

  
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/credts_helper.rb
module CredtsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_footer.html.haml
.footer__nav
  %h2 スマホでかんたんフリマアプリ
  %p 今すぐ無料ダウンロード！
  .footer__nav__apple-link
  .footer__nav__google-link
.footer__content
  .footer__content__1
    %h2 FURIMAについて
    %ul
      %li= link_to "会社概要（運営会社）", "#"
      %li= link_to "採用情報", "#"
      %li= link_to "プレスリリース", "#"
      %li= link_to "公式ブログ", "#"
      %li= link_to "FURIMAロゴ利用ガイドライン", "#"
      .footer__content__1__social
        %li
        = link_to "#" do
          %i.fav.fa-twitter
        %li
        = link_to "#" do
          = icon'fa','facebook-square'
  .footer__content__2
    %h2 FURIMAを見る
    %ul
      %li= link_to "カテゴリ一覧", "#"
      %li= link_to "ブランド一覧", "#"
      %li= link_to "FURIMAスタッフ注目トピック", "#"
  .footer__content__3
    %h2 ヘルプ＆ガイド
    %ul
      %li= link_to "FURIMAガイド", "#"
      %li= link_to "らくらくFURIMA便", "#"
      %li= link_to "ゆうゆうFURIMA便", "#"
      %li= link_to "大型FURIMA便", "#"
      %li= link_to "あんしん・あんぜん宣言！", "#"
      %li= link_to "偽ブランド品撲滅への取り組み", "#"
      %li= link_to "FURIMAボックス", "#"
  .footer__content__4
    %h2 プライバシーと利用規約
    %ul
      %li= link_to "プライバシーポリシー", "#"
      %li= link_to "FURIMA利用規約", "#"
      %li= link_to "あんしんスマホサポート制度に関する利用特約", "#"
      %li= link_to "コンプライアンスポリシー", "#"
.footer__bottom
  .footer__bottom__logo
    = image_tag "/logo/logo-white.png", alt: "", class:"image"
  .footer__bottom__copyright
  %span ©︎ 2020,Furima,Inc.

app/views/products/_header.html.haml
.header__top
  .header__top__logo
    %h1
      = link_to image_tag("/images/logo/logo.png", width: '120px', alt: "logo1"),root_path
  .search
    = form_tag() do
      %label.search__label
        = icon'fa', 'search', class: "search__label--icon"
      = text_field_tag :search, "",class:"search__field",placeholder:"何かお探しですか？"
.header__bottom
  .header__bottom__left
    %ul.header__bottom__left__categories
      %li
      = link_to root_path do
        =image_tag("/images/icon/icon_category.png", width: '20px', alt: "icon1")
        %span カテゴリから探す
      %li
      = link_to root_path do
        =image_tag("/images/icon/icon_brand.png", width: '20px', alt: "icon2")
        %span ブランドから探す
  .header__bottom__right
    .header__bottom__right__categories
      - if user_signed_in?
        = link_to "マイページ", user_path(current_user.id), class: "btn-registration"
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class:"btn-login"
      - else
        = link_to "新規会員登録", new_signup_path, class: "btn-registration"
        = link_to "ログイン", new_user_session_path, class:"btn-login"
        %end
      = link_to "FURIMAとは", root_path, class:"about-furima"

app/views/products/confirm.html.haml
//ヘッダー部分テンプレートに差し替え
.header2
  mercari
.buy-main
  .buy-main__container
    .buy-main__container__header
      購入内容の確認
    .buy-main__container__content
      .first_content
        = image_tag @product.images[0].image_url, id: "main_image"
      .sub_image
        - @product.images.each_with_index do |image, i|
          .sub_image_content
            = image_tag image.image_url, id: "image#{i+1}"



    .buy-main__container__status
      .buy-main__container__status__price
        %ul
          %h1.pay_price 支払い金額
          %li
            = @product.price
            %span 円 （税込）送料込み
      .buy-main__container__status__payment
        %ul
          %h3.method_payment 支払い方法  
          - if @card.blank?
            = link_to "カードを登録してください", new_credit_path, class: "create_credit_card_btn"
          -else
            クレジットカードを利用する
          
      .buy-main__container__status__delivery
        %ul
          %h3 配送先
          %li
          =link_to '#' do
            %span 登録してください
      .buy-main__container__status__btn
        %ul
          %li
            = form_tag(controller: :credits, action: :pay, method: :post) do
              %button 購入する
          %li
            = link_to "TOPへ戻る", root_path, class: 'confirm_home_btn'


//フッター部分テンプレートに差し替え
.footer
  .footer__box
    .footer__box__text
      プライバシーポリシー
    .footer__box__message
      メルカリ利用規約
    .footer__box__form
      特定商取引に関する表記
  .footer__logo
    mercari
    .footer__logo__text
      © Mercari, Inc.

app/views/products/edit.html.haml
.edit-preview
  .edit-header
    .single-container
      %header.single-header
        %h1
          =link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?73731125", alt: "mercari", class: "image"), root_path
      %main.single-main
        %section.l-single-container.buy-item-container
          #sell-container
            %div{"data-reactroot": ""}
              .sell-container-inner
  .edit-products
    = form_with model: @product, local: true do |f|
      .edit-products__name
        = @product.name
      .edit-contents
        .edit-first_content
          %ul.edit-first_content_image
            - @product.images.each_with_index do |img, num|
              = image_tag img.image_url, class: "preview_image change_image", id: "preview_image_id_#{num}"
            = f.fields_for :images do |i|
              .js-file_group{ data: { index: "#{i.index}" }}
                = i.file_field :image,"data-index": "#{i.index}",class: "js-file input_btn"
                %span.js-remove 削除
              - if @product.persisted?
                = i.check_box :_destroy, data: { index: i.index }, class: 'hidden-destroy'
            - if @product.persisted? && @product.images.length <= 4
              .js-file_group{ data: { index: "#{@product.images.count}" }}
                = file_field_tag :image, name: "product[images_attributes][#{@product.images.count}][image]", class: "js-file input_btn"
                %span.js-remove 削除
      .sell-content
        .form-group
          %label
            商品名
            %span.form-require
              必須

          = f.text_field :name, placeholder: "商品名（必須 40文字まで)", value: "#{@product.name}", class: "input-default"
        .form-group
          %label
            商品の説明
            %span.form-require
              必須

          = f.text_area :detail, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5", class: "textarea-default"
      .sell-content.clearfix
        %h3.sell-sub-head
          商品の詳細
        .sell-form-box
          .form-group
            %label
              カテゴリー
              %span.form-require
                必須


            %div
              .select-wrap
                %i.fa.fa-chevron-down
                = f.collection_select :category_id, @category, :id, :name, { prompt: "---" }, { class: "category_select-box", id: "category_select" }
              .product_select-children
            %label
              サイズ
              %span.form-require
                必須
            = f.collection_select :size_id, Size.all, :id, :name, prompt: "--", class: 'select-default'
              
          .form-group
            .form-group
              %label
                商品の状態
                %span.form-require
                  必須
              .select-wrap
                %i.icon-arrow-bottom

                = f.collection_select :condition_id, Condition.all, :id, :name, prompt: "--", class: 'select-default'

      .sell-content.clearfix
        %h3.sell-sub-head
          配送について
        .sell-form-box
          .form-group
            %label
              配送料の負担
              %span.form-require
                必須
            .select-wrap
              %i.icon-arrow-bottom

              = f.collection_select :payer_id, Payer.all, :id, :name, prompt: "--", class: 'select-default'

          .form-group
            %label
              発送元の地域
              %span.form-require
                必須
            .select-wrap
              %i.icon-arrow-bottom

              = f.collection_select :shippingaddress_id, Shippingaddress.all, :id, :name, prompt: "--", class: 'select-default'
          .form-group
            %label
              発送までの日数
              %span.form-require
                必須
            .select-wrap
              %i.icon-arrow-bottom

              = f.collection_select :shippingdate_id, Shippingdate.all, :id, :name, prompt: "--", class: 'select-default'
              
      .sell-content.clearfix
        %h3.sell-sub-head
          配送について
        .sell-form-box
          %ul.sell-price
            %li.form-team
              %label.l-left
                価格
                %span.form-require
                  必須
              .l-right.sell-price-input
                ¥
                %div
                  = f.text_field :price, placeholder: "例）300", value: "#{@product.price}", class: "input-fee"
            %li.clearfix
              .l-left
                販売手数料(10%)
              .l-right
                _
            %li.clearfix.bold
              .l-left
                販売利益
              .l-right
                _
        .edit-done1
          = f.submit '編集を完了する', class: 'edit-done2'
              
  %footer.single-footer
    %nav
      %ul.clearfix
        %li.first
          =link_to "プライバシーポリシー", "#", class: 'second'
        %li.first
          =link_to "メルカリ利用規約", "#", class: 'second'
        %li.first
          =link_to "特定商取引法に関する表記", "#", class: 'second'
    =link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?73731125", alt: "mercari", height: "65", width: "80", class: "single-footer-logo"), root_path
    %p
      %small.third 
        © Mercari, Inc.

app/views/products/index.html.haml
.header
  = render "header"
.main-image
  = image_tag "/images/pict/bg-mainVisual-pict_pc.jpg", class:"google_image", alt:""
  = image_tag "/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg"
  
.main
  .main__top
    .main__top__header
      %h2 人気のカテゴリー
    .main__top__pickups
      %li レディース
      %li メンズ
      %li 家電・スマホ

  - if @product.blank?
    .first 
  - else
    .first 
      - @product[0..4].each do |product|
        .first__contents
          .first__contents__box
            = link_to '', product_path(product.id), class: 'first__contents__box__link'
            .first__contents__box__img
              = image_tag product.images[0].image_url
            .first__contents__box__name
              = product.name
            .first__contents__box__price
              = "#{product.price}円"
            .first__contents__header
              .first__contents__header__name
              .first__contents__header__more
  - if @product[5..9].present?              
    .first
      - @product[5..9].each do |product|
        .first__contents
          .first__contents__box
            = link_to '', product_path(product.id), class: 'first__contents__box__link'
            .first__contents__box__img
              = image_tag product.images[0].image_url
            .first__contents__box__name
              = product.name
            .first__contents__box__price
              = "#{product.price}円"
            .first__contents__header
              .first__contents__header__name
              .first__contents__header__more
              
.footer
  = render 'footer'

.purchase-btn
  %span.purchase_text 出品
  - if user_signed_in?
    = link_to "", new_product_path, class: "adada"
    .fas.fa-camera
  - else
    = link_to "", new_user_session_path, class: "adada"
    .fas.fa-camera

app/views/products/new.html.haml
.single-container
  %header.single-header
    %h1
      =link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?73731125", alt: "mercari", class: "image"), root_path
  %main.single-main
    %section.l-single-container.buy-item-container
      #sell-container
        %div{"data-reactroot": ""}
          .sell-container-inner
            %h2.l-single-head
              商品の情報を入力
          = form_with(model: @product, url: products_path, local: true, multipart: true) do |f|
            .sell-form
              .sell-upload-box
                %h3.sell-upload-head
                  出品画像
                  %span.form-require
                    必須
                %p 最大5枚までアップロードできます
                .sell-dropbox-container.clearfix.state-image-number-10 
                  .sell-upload-items-container
                    .sell-upload-items.have-item-0
                      %ul
                  .sell-upload-drop-box.have-item-0
                    #image-box
                      #previews
                        = f.fields_for :images do |i|
                          = i.label :image, "画像を選択", class: "label_field", style: "background-color: white; width: 100px; height: 100px;"
                          .js-file_group{data: { id: "#{i.index}" }}
                            = i.file_field :image, class: "js-file", style: "display: none;"
                            .js-remove
                    %pre.visible-pc クリックしてファイルをアップロード
                    %i.icon-camera
              .sell-content
                .form-group
                  %label
                    商品名
                    %span.form-require
                      必須

                  = f.text_field :name, placeholder: "商品名（必須 40文字まで)", value: "", class: "input-default"
                .form-group
                  %label
                    商品の説明
                    %span.form-require
                      必須
  
                  = f.text_area :detail, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5", class: "textarea-default"
              .sell-content.clearfix
                %h3.sell-sub-head
                  商品の詳細
                .sell-form-box
                  .form-group
                    %label
                      カテゴリー
                      %span.form-require
                        必須


                    %div
                      .select-wrap
                        %i.fa.fa-chevron-down
                        = f.collection_select :category_id, @category, :id, :name, { prompt: "---" }, { class: "category_select-box", id: "category_select" }
                      .product_select-children
                    %label
                      サイズ
                      %span.form-require
                        必須
                    = f.collection_select :size_id, Size.all, :id, :name, prompt: "--", class: 'select-default'
                      
                  .form-group
                    .form-group
                      %label
                        商品の状態
                        %span.form-require
                          必須
                      .select-wrap
                        %i.icon-arrow-bottom

                        = f.collection_select :condition_id, Condition.all, :id, :name, prompt: "--", class: 'select-default'

              .sell-content.clearfix
                %h3.sell-sub-head
                  配送について
                .sell-form-box
                  .form-group
                    %label
                      配送料の負担
                      %span.form-require
                        必須
                    .select-wrap
                      %i.icon-arrow-bottom

                      = f.collection_select :payer_id, Payer.all, :id, :name, prompt: "--", class: 'select-default'

                  .form-group
                    %label
                      発送元の地域
                      %span.form-require
                        必須
                    .select-wrap
                      %i.icon-arrow-bottom

                      = f.collection_select :shippingaddress_id, Shippingaddress.all, :id, :name, prompt: "--", class: 'select-default'
                  .form-group
                    %label
                      発送までの日数
                      %span.form-require
                        必須
                    .select-wrap
                      %i.icon-arrow-bottom

                      = f.collection_select :shippingdate_id, Shippingdate.all, :id, :name, prompt: "--", class: 'select-default'
                      
              .sell-content.clearfix
                %h3.sell-sub-head
                  配送について
                .sell-form-box
                  %ul.sell-price
                    %li.form-team
                      %label.l-left
                        価格
                        %span.form-require
                          必須
                      .l-right.sell-price-input
                        ¥
                        %div
                          = f.text_field :price, placeholder: "例）300", value: "", class: "input-fee"
                    %li.clearfix
                      .l-left
                        販売手数料(10%)
                      .l-right
                        _
                    %li.clearfix.bold
                      .l-left
                        販売利益
                      .l-right
                        _
              .modal{role: "dialog", tabindex: "-1"}
                .modal-innner
              .sell-content.sell-btn-box
                %div
                  %p
                    =link_to "禁止されている出品", "#"
                    ,
                    =link_to "行為", "#" 
                    を必ずご確認ください
                  %p
                    またブランド品でシリアルナンバー等がある場合はご記載ください。
                    =link_to "偽ブランドの販売", "#"
                    は犯罪であり処罰される可能性があります。
                  %p
                    また、出品をもちまして
                    =link_to "加盟店規約", "#"
                    に同意したことになります。
                %button.btn-default.btn-red{type: "submit"}
                  出品する
                %button.btn-default.btn-gray{action: root_path}
                  もどる
  %footer.single-footer
    %nav
      %ul.clearfix
        %li.first
          =link_to "プライバシーポリシー", "#", class: 'second'
        %li.first
          =link_to "メルカリ利用規約", "#", class: 'second'
        %li.first
          =link_to "特定商取引法に関する表記", "#", class: 'second'
    =link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?73731125", alt: "mercari", height: "65", width: "80", class: "single-footer-logo"), root_path
    %p
      %small.third 
        © Mercari, Inc.
        

app/views/products/show.html.haml
.show_preview
  .header
    = render 'header'
  .products
    .products__name
      = @product.name
    .contents
      
      .first_content
        = image_tag @product.images[0].image_url, id: "main_image"
      .sub_image
        - @product.images.each_with_index do |image, i|
          .sub_image_content
            = image_tag image.image_url, id: "image#{i+1}"
            
      .price
        = @product.price
        円
        .price__payer
          .price__payer__tax
            (税込）
          .price__status__postage
            送料込み
        
      - if user_signed_in? && current_user.id == @product.user_id
        .buy
          .edit-btn
            = link_to '編集する', edit_product_path(@product.id), class: 'edit'
        .buy
          .delete-btn
            = link_to 'この商品を削除する', product_path(@product.id), method: :delete, class:'delete'
      - elsif user_signed_in? 
        .buy
          = link_to '購入画面に進む',  confirm_product_path, class: 'buy_btn'
      - else
        = link_to 'ログインへ', new_user_session_path
      .second_content
        .products_info
          %table
            %tr
              %th
                出品者
              %td
                = @product.user.nickname
            %tr
              %th
                カテゴリー
              %td
                = @product.category.name
            %tr
              %th
                商品のサイズ
              %td
                = @product.size.name
            %tr
              %th
                商品の状態
              %td
                = @product.condition.name
            %tr
              %th
                配送料の負担
              %td
                = @product.payer.name
            %tr
              %th
                発送元地域
              %td
                = @product.shippingaddress.name
            %tr
              %th
                発送予定日数
              %td
                = @product.shippingdate.name
      .option
        %ul.likes
          %i.fas.fa-star
          %li お気に入り 0
        %ul.report
          %i.fas.fa-flag
          %li 不適切な商品の通報

    .comment
      .comment__field
        .comment__field__info
          .user_name
            フリマさん
          .create_date
            2020年2月3日
        .comment__field__text
          お気に入りです。
        .comment__field__info
          .user_name
            フリマさん
          .create_date
            2020年2月3日
        .comment__field__text
          お気に入りです。
          
      .form
        = form_with local: true do |f|
          = f.text_area :detail, class: 'text_area'
          .text_note
            相手のことを考え丁寧なコメントを心がけましょう。
            %br/
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = f.submit 'コメントする',class: 'send_btn'
  %ul.btn
    %li
      = link_to '< 前へ', '#',class: 'left_btn'
    %li
      = link_to '次へ >', '#',class: 'right_btn'
  .item_more
    = link_to 'もっと見る','#',class: 'item_more__btn'
  .footer
    = render 'footer'